// Package ts11client is a reusable client for TS11 credential metadata
// registries (registry.siros.org and compatible registries generated by
// registry-cli). It resolves SD-JWT VC Type Metadata documents by their
// vct claim value, and mdoc/MDDL metadata documents by their doctype
// value, across one or more registries queried concurrently - the first
// registry to answer wins, so a slow or unreachable registry never blocks
// resolution as long as at least one configured registry (or a configured
// local override) has the answer.
package ts11client

import (
	"context"
	"errors"

	"github.com/sirosfoundation/go-ts11client/schemameta"
)

// ErrNotFound is returned (wrapped) when no configured local override or
// registry has an entry for the requested vct/doctype.
var ErrNotFound = errors.New("ts11client: not found")

// Resolved is the result of a successful resolution: the raw bytes of the
// resolved document, plus which format it is and where it came from.
// Callers decode Data into their own VCTM/MDDL type - this package does
// not impose one, matching how the rest of this document's format is
// already owned by each consumer.
type Resolved struct {
	Entry  schemameta.Entry
	Format schemameta.Format
	Data   []byte
	Source string // "local", or the base URL of the registry that answered
}

// Client resolves credential metadata by vct (SD-JWT VC) or doctype
// (mdoc), from local overrides and/or one or more TS11 registries.
type Client interface {
	// ResolveVCT resolves an SD-JWT VC Type Metadata document by its vct
	// claim value. Returns an error wrapping ErrNotFound if nothing has it.
	ResolveVCT(ctx context.Context, vct string) (*Resolved, error)
	// ResolveDoctype resolves an mdoc MDDL metadata document by its
	// doctype value. Returns an error wrapping ErrNotFound if nothing has it.
	ResolveDoctype(ctx context.Context, doctype string) (*Resolved, error)
}
