// Package schemameta holds the wire types for a TS11 registry's published
// discovery index and per-credential documents, matching the JSON shapes
// generated by registry-cli (https://github.com/sirosfoundation/registry-cli)
// and served statically by registry.siros.org and compatible registries.
package schemameta

import "encoding/json"

// Format identifies which credential format a FormatRef points to, matching
// the keys of an Entry's Formats map ("vctm", "mdoc", "vc").
type Format string

const (
	// FormatVCTM is an SD-JWT VC Type Metadata document (IETF SD-JWT VC).
	FormatVCTM Format = "vctm"
	// FormatMDOC is an ISO 18013-5/23220 mdoc MDDL metadata document.
	FormatMDOC Format = "mdoc"
	// FormatVC is a W3C Verifiable Credential schema document.
	FormatVC Format = "vc"
)

// FormatRef points to one format's served document for a credential.
type FormatRef struct {
	URL  string `json:"url"`
	Type string `json:"type"`
}

// Source records where a credential's definition originates, for
// provenance/debugging - not used for resolution.
type Source struct {
	Repository string `json:"repository,omitempty"`
	Branch     string `json:"branch,omitempty"`
}

// Metadata links to human/machine-readable views of a credential's
// canonical document.
type Metadata struct {
	HTML string `json:"html,omitempty"`
	JSON string `json:"json,omitempty"`
}

// Entry is one credential's entry in a registry's discovery index
// (".well-known/vctm-registry.json"). VCT is the index's primary key -
// every credential has one, even mdoc-only or W3C-VC-only credentials,
// though it usually IS the credential's real "vct" claim value for
// SD-JWT VC credentials. VCT is not necessarily a URL on the registry's
// own domain - it may be an arbitrary issuer-controlled identifier (a
// vct value can point at the issuer's own domain rather than the
// registry serving its metadata), so it must never be treated as a
// fetchable URL directly; always resolve through Formats instead.
type Entry struct {
	VCT          string               `json:"vct"`
	Name         string               `json:"name"`
	Description  string               `json:"description,omitempty"`
	Organization string               `json:"organization,omitempty"`
	Formats      map[Format]FormatRef `json:"formats"`
	Metadata     Metadata             `json:"metadata,omitempty"`
	Source       Source               `json:"source,omitempty"`
}

// Index is the full contents of a registry's
// ".well-known/vctm-registry.json" discovery document.
type Index struct {
	Schema      string  `json:"$schema,omitempty"`
	Name        string  `json:"name,omitempty"`
	Description string  `json:"description,omitempty"`
	URL         string  `json:"url,omitempty"`
	Version     string  `json:"version,omitempty"`
	Credentials []Entry `json:"credentials"`
}

// MDOCDocument is the shape of a resolved FormatMDOC document, used only
// to extract Doctype - callers decode the full document themselves (via
// Resolved.Data) into whatever type they already use for MDDL metadata.
type MDOCDocument struct {
	Doctype string `json:"doctype"`
}

// ExtractDoctype reads the "doctype" field out of a raw mdoc metadata
// document, without requiring the caller's own MDDL type.
func ExtractDoctype(data []byte) (string, error) {
	var doc MDOCDocument
	if err := json.Unmarshal(data, &doc); err != nil {
		return "", err
	}
	return doc.Doctype, nil
}
